// Generated by https://pagedraw.io/pages/10874
import React from 'react';
import {CircularProgress} from '@material-ui/core';
import {TextField} from '@material-ui/core';
import {Button} from '@material-ui/core';
import './home.css';


function render() {
    return <div className="home-home-5">
        <div className="home-0">
            <div className="home-rectangle-9">
                <div className="home-0-0-0">
                    <div className="home-0-0-0-0">
                        <div className="home-0-0-0-0-0">
                            <div className="home-text-6">
                                Welcome to Pagedraw + Rekit
                            </div>
                        </div>
                    </div>
                    <div className="home-circularprogress_instance-0">
                        <CircularProgress color={"primary"} thickness={6} size={50} value={50} variant={"indeterminate"} /> 
                    </div>
                </div>
                <div className="home-0-0-1">
                    <div className="home-textfield_instance-5">
                        <TextField defaultValue={""} helperText={""} label={"Username"} disabled={false} error={false} fullWidth={true} /> 
                    </div>
                </div>
                <div className="home-0-0-2">
                    <div className="home-textfield_instance-2">
                        <TextField defaultValue={""} helperText={""} label={"Email"} disabled={false} error={false} fullWidth={true} /> 
                    </div>
                </div>
                <div className="home-0-0-3">
                    <div onClick={this.props.clickButton} className="home-button_instance-3">
                        <Button variant={"raised"} size={"medium"} color={"primary"} children={"Click me"} disabled={false} fullWidth={true} /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="home-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
